

// import { useEffect, useState } from "react";
// import API from "../../services/api";
// import jsPDF from "jspdf";

// const TransactionHistory = () => {

//   const [data, setData] = useState([]);

//   useEffect(() => {
//     const fetchData = async () => {
//       const res = await API.get("/transaction/history");
//       setData(res.data);
//     };

//     fetchData();
//   }, []);

//   // 🔥 Single PDF
//   const downloadSingle = (item) => {
//   const doc = new jsPDF();

//   // Header
//   doc.setFontSize(18);
//   doc.text("MyBank", 20, 20);

//   doc.setFontSize(12);
//   doc.text("Transaction Receipt", 20, 30);

//   // Line
//   doc.line(20, 35, 190, 35);

//   // Details
//   doc.setFontSize(12);

//   let y = 50;

//   doc.text(`Transaction Type: ${item.type}`, 20, y);
//   y += 10;

//   doc.text(`Amount: ₹${item.amount}`, 20, y);
//   y += 10;

//   if (item.sender) {
//     doc.text(`Sender: ${item.sender.name}`, 20, y);
//     y += 10;
//   }

//   if (item.receiver) {
//     doc.text(`Receiver: ${item.receiver.name}`, 20, y);
//     y += 10;
//   }

//   // Date
//   const date = new Date().toLocaleString();
//   doc.text(`Date: ${date}`, 20, y + 10);

//   // Footer
//   doc.setFontSize(10);
//   doc.text("Thank you for banking with us 💙", 20, 280);

//   doc.save("transaction-receipt.pdf");
// };


//   // 🔥 All Transactions PDF
// const downloadAll = () => {
//   const doc = new jsPDF();

//   // Header
//   doc.setFontSize(18);
//   doc.text("MyBank", 20, 20);

//   doc.setFontSize(12);
//   doc.text("All Transactions Report", 20, 30);

//   doc.line(20, 35, 190, 35);

//   let y = 50;

//   // Table Header
//   doc.setFontSize(11);
//   doc.text("No", 20, y);
//   doc.text("Type", 40, y);
//   doc.text("Amount", 90, y);
//   doc.text("User", 140, y);

//   y += 10;

//   // Table Data
//   data.forEach((item, index) => {
//     doc.text(`${index + 1}`, 20, y);
//     doc.text(`${item.type}`, 40, y);
//     doc.text(`₹${item.amount}`, 90, y);

//     const name =
//       item.receiver?.name ||
//       item.sender?.name ||
//       "Self";

//     doc.text(name, 140, y);

//     y += 10;

//     // Page break
//     if (y > 270) {
//       doc.addPage();
//       y = 20;
//     }
//   });

//   // Footer
//   doc.setFontSize(10);
//   doc.text("Generated by MyBank", 20, 280);

//   doc.save("transactions-report.pdf");
// };


//   return (
//     <div className="mt-6 px-4">

//       <div className="glass-card p-6 md:p-8">

//         {/* Title + All PDF */}
//         <div className="flex justify-between items-center mb-4 flex-wrap gap-3">
//           <h2 className="section-title">
//             Transaction History
//           </h2>

//           <button
//             onClick={downloadAll}
//             className="btn-primary text-sm"
//           >
//             Download All PDF
//           </button>
//         </div>

//         {data.length === 0 ? (
//           <p className="text-gray-400 text-center text-sm md:text-base">
//             No transactions found
//           </p>
//         ) : (
//           <div className="space-y-4 mt-4">

//             {data.map((item) => {

//               // 🟢 Deposit
//               if (item.type === "deposit") {
//                 return (
//                   <div
//                     key={item._id}
//                     className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10"
//                   >
//                     <p className="text-sm md:text-base text-gray-200">
//                       Deposit
//                     </p>

//                     <div className="flex items-center gap-3">
//                       <p className="text-green-400 font-semibold">
//                         +₹{item.amount}
//                       </p>

//                       <button
//                         onClick={() => downloadSingle(item)}
//                         className="btn-secondary text-xs"
//                       >
//                         PDF
//                       </button>
//                     </div>
//                   </div>
//                 );
//               }

//               // 🔴 Sent
//               if (item.sender?._id === item.user) {
//                 return (
//                   <div
//                     key={item._id}
//                     className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10"
//                   >
//                     <p className="text-sm md:text-base text-gray-200">
//                       Sent to {item.receiver?.name}
//                     </p>

//                     <div className="flex items-center gap-3">
//                       <p className="text-red-400 font-semibold">
//                         -₹{item.amount}
//                       </p>

//                       <button
//                         onClick={() => downloadSingle(item)}
//                         className="btn-secondary text-xs"
//                       >
//                         PDF
//                       </button>
//                     </div>
//                   </div>
//                 );
//               }

//               // 🔵 Received
//               // return (
//               //   <div
//               //     key={item._id}
//               //     className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10"
//               //   >
//               //     <p className="text-sm md:text-base text-gray-200">
//               //       Received from {item.sender?.name}
//               //     </p>

//               //     <div className="flex items-center gap-3">
//               //       <p className="text-blue-400 font-semibold">
//               //         +₹{item.amount}
//               //       </p>

//               //       <button
//               //         onClick={() => downloadSingle(item)}
//               //         className="btn-secondary text-xs"
//               //       >
//               //         PDF
//               //       </button>
//               //     </div>
//               //   </div>
//               // );


//               // 🔵 Received
//               return (
//                 <div
//                   key={item._id}
//                   className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10"
//                 >
//                   <div>
//                     <p className="text-gray-200">
//                       Received from{" "}
//                       <span className="font-semibold text-white">
//                         {item.sender?.name || item.sender?.email || "Unknown User"}
//                       </span>
//                     </p>

//                     <p className="text-xs text-gray-400">
//                       {item.sender?.email}
//                     </p>
//                   </div>

//                   <div className="flex items-center gap-3">
//                     <p className="text-blue-400 font-semibold">
//                       +₹{item.amount}
//                     </p>

//                     <button
//                       onClick={() => downloadSingle(item)}
//                       className="btn-secondary text-xs"
//                     >
//                       PDF
//                     </button>
//                   </div>
//                 </div>
//               );



//             })}

//           </div>
//         )}

//       </div>

//     </div>
//   );
// };

// export default TransactionHistory;


// import { useEffect, useState } from "react";
// import API from "../../services/api";
// import jsPDF from "jspdf";
// import { PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer } from "recharts";

// const TransactionHistory = () => {

//   const [data, setData] = useState([]);

//   useEffect(() => {
//     const fetchData = async () => {
//       const res = await API.get("/transaction/history");
//       setData(res.data);
//     };

//     fetchData();
//   }, []);

//   // 📊 🔥 CALCULATE TOTALS
//   let totalDeposit = 0;
//   let totalSent = 0;
//   let totalReceived = 0;

//   data.forEach((item) => {
//     if (item.type === "deposit") {
//       totalDeposit += item.amount;
//     } else if (item.sender?._id === item.user) {
//       totalSent += item.amount;
//     } else {
//       totalReceived += item.amount;
//     }
//   });

//   const chartData = [
//     { name: "Deposit", value: totalDeposit },
//     { name: "Sent", value: totalSent },
//     { name: "Received", value: totalReceived },
//   ];

//   // 🔥 Single PDF
//   const downloadSingle = (item) => {
//     const doc = new jsPDF();

//     doc.setFontSize(18);
//     doc.text("MyBank", 20, 20);

//     doc.setFontSize(12);
//     doc.text("Transaction Receipt", 20, 30);

//     doc.line(20, 35, 190, 35);

//     let y = 50;

//     doc.text(`Transaction Type: ${item.type}`, 20, y);
//     y += 10;

//     doc.text(`Amount: ₹${item.amount}`, 20, y);
//     y += 10;

//     if (item.sender) {
//       doc.text(`Sender: ${item.sender.name}`, 20, y);
//       y += 10;
//     }

//     if (item.receiver) {
//       doc.text(`Receiver: ${item.receiver.name}`, 20, y);
//       y += 10;
//     }

//     const date = new Date().toLocaleString();
//     doc.text(`Date: ${date}`, 20, y + 10);

//     doc.setFontSize(10);
//     doc.text("Thank you for banking with us 💙", 20, 280);

//     doc.save("transaction-receipt.pdf");
//   };

//   // 🔥 All PDF
//   const downloadAll = () => {
//     const doc = new jsPDF();

//     doc.text("MyBank", 20, 20);
//     doc.text("All Transactions Report", 20, 30);

//     doc.line(20, 35, 190, 35);

//     let y = 50;

//     doc.text("No", 20, y);
//     doc.text("Type", 40, y);
//     doc.text("Amount", 90, y);
//     doc.text("User", 140, y);

//     y += 10;

//     data.forEach((item, index) => {
//       doc.text(`${index + 1}`, 20, y);
//       doc.text(`${item.type}`, 40, y);
//       doc.text(`₹${item.amount}`, 90, y);

//       const name =
//         item.receiver?.name ||
//         item.sender?.name ||
//         "Self";

//       doc.text(name, 140, y);

//       y += 10;

//       if (y > 270) {
//         doc.addPage();
//         y = 20;
//       }
//     });

//     doc.text("Generated by MyBank", 20, 280);

//     doc.save("transactions-report.pdf");
//   };

//   return (
//     <div className="mt-6 px-4">

//       <div className="glass-card p-6 md:p-8">

//         {/* TITLE */}
//         <div className="flex justify-between items-center mb-4 flex-wrap gap-3">
//           <h2 className="section-title">
//             Transaction History
//           </h2>

//           <button onClick={downloadAll} className="btn-primary text-sm">
//             Download All PDF
//           </button>
//         </div>

//         {/* 📊 GRAPH */}
//         <div className="glass-card p-4 mb-6">
//           <h3 className="text-center mb-4 font-semibold">
//             Transaction Overview 📊
//           </h3>

//           <div className="w-full h-64">
//             <ResponsiveContainer>
//               <PieChart>
//                 <Pie
//                   data={chartData}
//                   dataKey="value"
//                   outerRadius={80}
//                   label
//                 >
//                   <Cell fill="#22c55e" /> {/* Deposit */}
//                   <Cell fill="#ef4444" /> {/* Sent */}
//                   <Cell fill="#3b82f6" /> {/* Received */}
//                 </Pie>
//                 <Tooltip />
//                 <Legend />
//               </PieChart>
//             </ResponsiveContainer>
//           </div>
//         </div>

//         {/* LIST */}
//         {data.length === 0 ? (
//           <p className="text-gray-400 text-center">
//             No transactions found
//           </p>
//         ) : (
//           <div className="space-y-4">

//             {data.map((item) => {

//               if (item.type === "deposit") {
//                 return (
//                   <div key={item._id} className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10">
//                     <p>Deposit</p>

//                     <div className="flex gap-3">
//                       <p className="text-green-400">+₹{item.amount}</p>
//                       <button onClick={() => downloadSingle(item)} className="btn-secondary text-xs">PDF</button>
//                     </div>
//                   </div>
//                 );
//               }

//               if (item.sender?._id === item.user) {
//                 return (
//                   <div key={item._id} className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10">
//                     <p>Sent to {item.receiver?.name}</p>

//                     <div className="flex gap-3">
//                       <p className="text-red-400">-₹{item.amount}</p>
//                       <button onClick={() => downloadSingle(item)} className="btn-secondary text-xs">PDF</button>
//                     </div>
//                   </div>
//                 );
//               }

//               return (
//                 <div key={item._id} className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10">
//                   <div>
//                     <p>
//                       Received from <span className="font-semibold">
//                         {item.sender?.name || item.sender?.email}
//                       </span>
//                     </p>
//                     <p className="text-xs text-gray-400">
//                       {item.sender?.email}
//                     </p>
//                   </div>

//                   <div className="flex gap-3">
//                     <p className="text-blue-400">+₹{item.amount}</p>
//                     <button onClick={() => downloadSingle(item)} className="btn-secondary text-xs">PDF</button>
//                   </div>
//                 </div>
//               );

//             })}

//           </div>
//         )}

//       </div>

//     </div>
//   );
// };

// export default TransactionHistory;


import { useEffect, useState } from "react";
import API from "../../services/api";
import jsPDF from "jspdf";
import { PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer } from "recharts";

const TransactionHistory = () => {

  const [data, setData] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const res = await API.get("/transaction/history");
      setData(res.data);
    };

    fetchData();
  }, []);

  // 📊 TOTAL CALCULATION
  let totalDeposit = 0;
  let totalSent = 0;
  let totalReceived = 0;

  data.forEach((item) => {
    if (item.type === "deposit") {
      totalDeposit += item.amount;
    } else if (item.sender?._id === item.user) {
      totalSent += item.amount;
    } else {
      totalReceived += item.amount;
    }
  });

  const chartData = [
    { name: "Deposit", value: totalDeposit },
    { name: "Sent", value: totalSent },
    { name: "Received", value: totalReceived },
  ];

  // 🔥 SINGLE PDF
  const downloadSingle = (item) => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("MyBank", 20, 20);

    doc.setFontSize(12);
    doc.text("Transaction Receipt", 20, 30);

    doc.line(20, 35, 190, 35);

    let y = 50;

    doc.text(`Transaction Type: ${item.type}`, 20, y);
    y += 10;

    doc.text(`Amount: ₹${item.amount}`, 20, y);
    y += 10;

    if (item.sender) {
      doc.text(`Sender: ${item.sender.name}`, 20, y);
      y += 10;
    }

    if (item.receiver) {
      doc.text(`Receiver: ${item.receiver.name}`, 20, y);
      y += 10;
    }

    const date = new Date().toLocaleString();
    doc.text(`Date: ${date}`, 20, y + 10);

    doc.setFontSize(10);
    doc.text("Thank you for banking with us 💙", 20, 280);

    doc.save("transaction-receipt.pdf");
  };

  // 🔥 ALL PDF
  const downloadAll = () => {
    const doc = new jsPDF();

    doc.text("MyBank", 20, 20);
    doc.text("All Transactions Report", 20, 30);

    doc.line(20, 35, 190, 35);

    let y = 50;

    doc.text("No", 20, y);
    doc.text("Type", 40, y);
    doc.text("Amount", 90, y);
    doc.text("User", 140, y);

    y += 10;

    data.forEach((item, index) => {
      doc.text(`${index + 1}`, 20, y);
      doc.text(`${item.type}`, 40, y);
      doc.text(`₹${item.amount}`, 90, y);

      const name =
        item.receiver?.name ||
        item.sender?.name ||
        "Self";

      doc.text(name, 140, y);

      y += 10;

      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    });

    doc.text("Generated by MyBank", 20, 280);

    doc.save("transactions-report.pdf");
  };

  return (
    <div className="mt-6 px-4 md:px-6 lg:px-8">

      <div className="glass-card p-4 md:p-6 lg:p-8">

        {/* TITLE */}
        <div className="flex justify-between items-center mb-4 flex-wrap gap-3">
          <h2 className="section-title">
            Transaction History
          </h2>

          <button onClick={downloadAll} className="btn-primary text-sm">
            Download All PDF
          </button>
        </div>

        {/* 📊 RESPONSIVE GRAPH */}
        <div className="glass-card p-4 md:p-6 mb-6">

          <h3 className="text-center text-base md:text-lg font-semibold mb-4">
            Transaction Overview 📊
          </h3>

          <div className="w-full h-55 sm:h-65 md:h-75 lg:h-87.5">

            <ResponsiveContainer width="100%" height="100%">
              <PieChart>

                <Pie
                  data={chartData}
                  dataKey="value"
                  cx="50%"
                  cy="50%"
                  innerRadius={40}
                  outerRadius={80}
                  paddingAngle={5}
                  label={({ name, percent }) =>
                    `${name} ${(percent * 100).toFixed(0)}%`
                  }
                >
                  <Cell fill="#22c55e" />
                  <Cell fill="#ef4444" />
                  <Cell fill="#3b82f6" />
                </Pie>

                <Tooltip
                  contentStyle={{
                    backgroundColor: "#1E293B",
                    border: "none",
                    borderRadius: "10px",
                    color: "white"
                  }}
                />

                <Legend wrapperStyle={{ fontSize: "12px" }} />

              </PieChart>
            </ResponsiveContainer>

          </div>

        </div>

        {/* LIST */}
        {data.length === 0 ? (
          <p className="text-gray-400 text-center">
            No transactions found
          </p>
        ) : (
          <div className="space-y-4">

            {data.map((item) => {

              if (item.type === "deposit") {
                return (
                  <div key={item._id} className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10">
                    <p>Deposit</p>

                    <div className="flex gap-3">
                      <p className="text-green-400">+₹{item.amount}</p>
                      <button onClick={() => downloadSingle(item)} className="btn-secondary text-xs">PDF</button>
                    </div>
                  </div>
                );
              }

              if (item.sender?._id === item.user) {
                return (
                  <div key={item._id} className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10">
                    <p>Sent to {item.receiver?.name}</p>

                    <div className="flex gap-3">
                      <p className="text-red-400">-₹{item.amount}</p>
                      <button onClick={() => downloadSingle(item)} className="btn-secondary text-xs">PDF</button>
                    </div>
                  </div>
                );
              }

              return (
                <div key={item._id} className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/10">
                  <div>
                    <p>
                      Received from <span className="font-semibold">
                        {item.sender?.name || item.sender?.email}
                      </span>
                    </p>
                    <p className="text-xs text-gray-400">
                      {item.sender?.email}
                    </p>
                  </div>

                  <div className="flex gap-3">
                    <p className="text-blue-400">+₹{item.amount}</p>
                    <button onClick={() => downloadSingle(item)} className="btn-secondary text-xs">PDF</button>
                  </div>
                </div>
              );

            })}

          </div>
        )}

      </div>

    </div>
  );
};

export default TransactionHistory;